# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-04 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pode', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercode',
            options={'verbose_name': 'User code asset'},
        ),
        migrations.AlterUniqueTogether(
            name='usercode',
            unique_together=set([('owner', 'slug')]),
        ),
    ]
